Capstone Module 2
Iqbal-Elham/Capstone-module-2 pull request #39
Opened 2023-01-05 22:47 UTC by Iqbal-Elham

## JavaScript Capstone Project
In this project we build a API-based web-app that it has homepage, comment popup, and reservation popup, so we get the movies from the API and then we can like, give comment and reserve the movies and count each of them.
### The requirements needed:
- Using the Html/CSS
- Using JavaScript ES6 and make the code asynchronous 
- Using the linter for free of errors and beautiful coding.
- Using GitHub flow.
- Documented in a professional way and record a video.
- Using webpack, and modules
- Use AAA pattern for unit tests.
- Use API documentation.

2023-01-05 23:52 UTC, Owusu-Desmond requested changes
Hi @Iqbal-Elham, @belaymit and @dgcuenca :wave:  

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

<img src="https://media1.giphy.com/media/h7u3pLvYK3HfQ4yXxW/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the setup of the project ✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-05 23:52 UTC, Owusu-Desmond commented on src/modules/populateData.js
> +            alarmFormReservations.innerHTML = 'Reservation Completed';
- [ OPTIONAL] Most times successful messages have the color to be green and errors have their colors to be red so I think it is better if you make the `Reservation Completed` alert her have green color to differentiate the itself from the error massages :blush:

2023-01-05 23:52 UTC, Owusu-Desmond commented on src/style.css
> +
- [ ] From the project requirements, you expected to adhere to this given design in terms of the data displayed on the page by comparing your design and the given design your popup does not look like the given popup page design.

 comparing the differences... 
  - the given design has no nav for the popup page but I can still see your nav clearly for your popup page
  - I can clearly see your home page cards in the popup page

| Your Design |Given Design |
| :---:   | :---: | 
| ![Screenshot from 2023-01-05 23-32-57](https://user-images.githubusercontent.com/92303891/210900382-fadaaca8-dba5-4df5-9002-5345c16aa836.png) | ![image](https://user-images.githubusercontent.com/92303891/210899504-7815779e-8298-4669-8854-025a8d64ec17.png)|

I think is better if you enlarge the popup window and blur the background to differentiate the two pages ie. (the home page and the popup page)

2023-01-05 23:52 UTC, Owusu-Desmond commented on README.md
> +  <img src="./src/assets/favicon-images/murple_logo.png" alt="logo" width="150"  height="auto" />
- [ ] Please make sure you remove this microverse logo from your readme. It is meant to be replaced with your project logo if you have one. :pray:

2023-01-06 07:58 UTC, emmiiorji approved these changes
Hi @Iqbal-Elham, @belaymit and @dgcuenca,

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Congrats](https://user-images.githubusercontent.com/20554583/210347504-5d934a2f-a268-44e8-8735-2eb0a14725bb.gif)

## Good Highlights✔️

- Good commit messages
- Adhered to Gitflow
- Linter checks are passing
- Requested change has been implemented


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-06 08:53 UTC, merged